# Generated by Django 4.0.1 on 2022-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReceived', models.DateField()),
                ('product', models.CharField(max_length=30)),
                ('issue', models.CharField(max_length=30)),
                ('narrative', models.TextField()),
                ('company', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('consent', models.CharField(max_length=30)),
                ('category_id', models.CharField(max_length=30)),
            ],
        ),
    ]
