# Generated by Django 4.0.1 on 2022-02-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complains',
            new_name='Complaints',
        ),
    ]
