# Generated by Django 4.0.1 on 2022-03-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_complains_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='category_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='consent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='dateReceived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='issue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='product',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
