# Generated by Django 4.0.1 on 2022-03-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_complaints_customer_disputed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='category_id',
        ),
    ]
