# Generated by Django 4.0.1 on 2022-03-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_complaints_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReceived', models.DateField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=30, null=True)),
                ('issue', models.CharField(blank=True, max_length=30, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('consent', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_disputed', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_timely_responded', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
