# Generated by Django 4.0.1 on 2022-04-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newcomplaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcomplaints',
            name='customer_disputed',
        ),
        migrations.RemoveField(
            model_name='newcomplaints',
            name='customer_timely_responded',
        ),
    ]
