# Generated by Django 4.0.1 on 2022-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_newcomplaints_customer_disputed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcomplaints',
            name='customer_disputed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newcomplaints',
            name='customer_timely_responded',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
    ]
